[package]
name = "ham-lsp"
version = "0.1.1"
authors = ["vain0x <vainzerox@gmail.com>"]
edition = "2018"

[dependencies]
encoding = "0.2"
glob = "0.3"
log = "0.4"
lsp-types = "0.56"
notify = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simplelog = "0.7"
