[package]
name = "ham-core"
version = "0.3.0"
authors = ["vain0x <vainzerox@gmail.com>"]
edition = "2018"

[dependencies]
encoding = "0.2"
glob = "0.3"
log = "0.4"
lsp-types = { version = "0.74", features = ["proposed"] }
notify = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simplelog = "0.7"
